# Generated by Django 4.1.5 on 2023-01-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportboard', '0004_alter_supportrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(default='Aktiv', max_length=254),
        ),
    ]
