# Generated by Django 4.1.5 on 2023-01-11 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supportboard', '0005_alter_supportrequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportrequest',
            options={'verbose_name_plural': 'Support Requests'},
        ),
        migrations.RemoveField(
            model_name='supportrequest',
            name='status',
        ),
    ]
