# Generated by Django 4.1.5 on 2023-01-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportboard', '0006_alter_supportrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportrequest',
            options={},
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(default='Open', editable=False, max_length=254, null=True),
        ),
    ]
