# Generated by Django 4.1.5 on 2023-01-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportboard', '0007_alter_supportrequest_options_supportrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(default='Open', editable=False, max_length=254),
        ),
    ]
