# Generated by Django 4.1.5 on 2023-01-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportboard', '0009_alter_supportrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Waiting', 'Waiting'), ('Done', 'Done')], default='Open', max_length=254),
        ),
    ]
