# Generated by Django 4.1.5 on 2023-01-12 07:26

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berufsbildner',
            fields=[
            ],
            options={
                'verbose_name': 'Berufsbildner',
                'verbose_name_plural': 'Berufsbildner',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
            ],
            options={
                'verbose_name': 'Developer',
                'verbose_name_plural': 'Developer',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Lernende',
            fields=[
            ],
            options={
                'verbose_name': 'Lernende',
                'verbose_name_plural': 'Lernende',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
